# Generated by Django 3.0.7 on 2020-06-15 04:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('home', '0004_agriindexpage_agripage_blogpagegalleryimage_servicespage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServicesPage',
            new_name='ProductsIndexPage',
        ),
        migrations.RenameModel(
            old_name='AgriPage',
            new_name='ProductsPage',
        ),
        migrations.DeleteModel(
            name='AgriIndexPage',
        ),
    ]
