# Generated by Django 3.0.7 on 2020-06-15 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('home', '0005_auto_20200615_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='productspage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='BlogPageGalleryImage',
        ),
        migrations.DeleteModel(
            name='ProductsIndexPage',
        ),
        migrations.DeleteModel(
            name='ProductsPage',
        ),
    ]
