# Generated by Django 3.0.7 on 2020-06-19 06:41

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_delete_productsindexpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
